---
- name: Conditionals
  hosts: all
  remote_user: ansible
  tasks:
  - name: Debian?
    debug: msg="Hallo von Debian"
    when: ansible_os_family=="Debian"

  - name: Centos?
    debug: msg="Hallo von Centos"
    when: ansible_os_family=="Centos"



- name: Installiere Webserver
  hosts: all
  remote_user: ansible
  become: true
  tasks:
  - name: Setze Distributionsvariablen Debian
    set_fact:
      webserver: apache2
    when: ansible_os_family=="Debian"

  - name: Setze Distributionsvariablen Centos
    set_fact:
      webserver: httpd
    when: ansible_os_family=="Centos"

  - name: Starte webserver
    service: name={{ webserver }} state=started
